services:
  
  app:
  # ใช้ตอน deploy
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}      
    ports:
      - "3000:3000"                 
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - db
    networks:
      - app-networks
    
      
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-networks
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: fastapi-backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ZILLIZ_URI: ${ZILLIZ_URI}
      ZILLIZ_TOKEN: ${ZILLIZ_TOKEN}
    ports:
      - "8000:8000"
    networks:
      - app-networks
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  pg_data:

networks:
  app-networks:
    driver: bridge
